import Applicant from "@/interfaces/Applicant";

const MockApplicants: Applicant[] = [
    {
        applicationID: 1,
        fullName: "Hanne Marie Haakaas",
        ntnuUsername: "hannmhaa",
        email: "hanne.haakaas@gmail.com",
        phoneNumber: "90095630",
        fieldOfStudy: "Datateknologi",
        yearOfStudy: 2,
        experience: "Hei! Jeg kan ingenting, så my experience er null haha rip",
        aboutYou: "Jeg er en bonde fra østfold som legger trøkk på første stavelsen.",
        accepted: false,
        keep: false,
        rejectTime: new Date(),
    },
    {
        applicationID: 2,
        fullName: "Jens Nikolai Haakaas",
        ntnuUsername: "jensemann",
        email: "jens.haakaas@gmail.com",
        phoneNumber: "11223344",
        fieldOfStudy: "IT og Informasjonssystemer",
        yearOfStudy: 1,
        experience: "Hei! Min experience er at jeg er megaproff.",
        aboutYou: "Jeg er broren til Hanne.",
        accepted: false,
        keep: false,
        rejectTime: new Date(),
    },
    {
        applicationID: 3,
        fullName: "Ada Lovelace",
        ntnuUsername: "adaaa",
        email: "ada.lovelace@gmail.com",
        phoneNumber: "12345678",
        fieldOfStudy: "Influencer",
        yearOfStudy: 4,
        experience: "Google me.",
        aboutYou: "You should know who I am.",
        accepted: false,
        keep: false,
        rejectTime: new Date(),
    },
    {
        applicationID: 4,
        fullName: "Charles Babbage",
        ntnuUsername: "charlie",
        email: "charles.babbage@gmail.com",
        phoneNumber: "13243546",
        fieldOfStudy: "Mathematics",
        yearOfStudy: 5,
        experience: "I basically invented the computer.",
        aboutYou: "I am British. Do you need to know more?",
        accepted: false,
        keep: false,
        rejectTime: new Date(),
    },
    {
        applicationID: 5,
        fullName: "Alan Turing",
        ntnuUsername: "theMachine",
        email: "alan.turing@gmail.com",
        phoneNumber: "31415926",
        fieldOfStudy: "Cryptography",
        yearOfStudy: 2,
        experience: "I beat the enigma!",
        aboutYou: "I'm smart.",
        accepted: false,
        keep: false,
        rejectTime: new Date(),
    },
]

export default MockApplicants;